### ISSUE TITLE
About Abstract of Daily Papers - Hugging Face

### ISSUE THREAD

**Issue by bc-li** [tongyx361/Awesome-LLM-Research#1]
Hi Yuxuan,

Thanks for putting together this awesome repository! It's super interesting and I really appreciate your efforts.

I have a small (and perhaps slightly irrelevant) question: I'm curious about how you discovered that the "Daily Papers - Hugging Face" is curated by Andrej Karpathy. From what I've found, aside from the Daily Papers Twitter account @ _akhaliq sharing the same initials as Andrej Karpathy, there doesn't seem to be a clear connection :)

Best,
Bocheng

**Comment by tongyx361** [comment]
Thanks a lot for your reminding! 😇 I have been always taking _akhaliq as Andrej Karpathy before today. I will fix it immediately!
